services:
  redis:
    container_name: redis-fc
    image: redis:7.2.4
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
  db:
    container_name: db-fc
    image: postgres:17.2
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/
    # env_file:
    #   - ./envs/dev/django/.env
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    restart: always
  

  backend:
    container_name: backend-fc
    build:    
      context: .
      dockerfile: ./dockerfiles/dev/django/Dockerfile
    volumes:
      - ./core:/usr/src/app
    working_dir: /usr/src/app
    # command: django-admin startproject core .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"    
    # env_file:
    #   - ./envs/dev/django/.env.sample
    restart: always
    depends_on:
      - db
      - redis
  
  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - '5000:80' # the port the web interface
      - '25:25' # the port the SMTP server
      - '143:143' # the port the IMAP server
    volumes:      
        - smtp4dev-data:/smtp4dev # This is where smtp4dev stores the database..
    environment:
      - ServerOptions__Urls=http://*:80
      #Specifies the server hostname. Used in auto-generated TLS certificate if enabled.
      - ServerOptions__HostName=smtp4dev

volumes:
  postgres_data:
  redis_data:
  smtp4dev-data:





